#!/usr/bin/env bash
# Regenerate companion/requirements.txt with sha256 hashes for EVERY wheel the companion needs,
# for CPython 3.11 on manylinux x86_64 and aarch64 (the add-on and Docker images are Debian bookworm).
# Usage: tools/pin_companion_requirements.sh   (needs network; uses companion/.venv's pip)
set -euo pipefail
cd "$(dirname "$0")/.."
PIP=companion/.venv/bin/pip
TOP=("paho-mqtt==2.1.0" "onnxruntime==1.22.1" "numpy==2.2.6" "pillow==11.3.0")
work=$(mktemp -d)
for arch in x86_64 aarch64; do
  $PIP download -q --only-binary=:all: --python-version 3.11 --implementation cp --abi cp311 --abi abi3 --abi none \
    --platform "manylinux_2_28_$arch" --platform "manylinux_2_17_$arch" --platform "manylinux2014_$arch" --platform any \
    -d "$work" "${TOP[@]}"
done
{
  echo "# GENERATED by tools/pin_companion_requirements.sh — do not edit by hand."
  echo "# CPython 3.11, manylinux x86_64 + aarch64 wheels, every transitive dependency, sha256-pinned."
  echo "# Rebuild after bumping a version; pip refuses anything not listed here (--require-hashes)."
  python3 - "$work" <<'PY'
import hashlib, re, sys
from collections import defaultdict
from pathlib import Path
work = Path(sys.argv[1])
groups = defaultdict(list)
for whl in sorted(work.glob("*.whl")):
    m = re.match(r"([A-Za-z0-9_.]+)-([0-9][^-]*)-", whl.name)
    name, ver = m.group(1).replace("_", "-").lower(), m.group(2)
    groups[(name, ver)].append(hashlib.sha256(whl.read_bytes()).hexdigest())
for (name, ver), hashes in sorted(groups.items()):
    print(f"{name}=={ver} \\")
    hs = sorted(set(hashes))
    for i, h in enumerate(hs):
        end = "" if i == len(hs) - 1 else " \\"
        print(f"    --hash=sha256:{h}{end}")
PY
} > companion/requirements.txt
rm -rf "$work"
echo "wrote companion/requirements.txt:"; grep -c "==" companion/requirements.txt
